services:
  db:
    image: postgres:16
    container_name: fichamepe_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: fichamepe
      POSTGRES_PASSWORD: fichamepe123
      POSTGRES_DB: fichamepe_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
